[package]
name = "jamkit"
version = "0.1.2"
description = "A small game development library."
authors = ["Layl Conway"]
license = "Apache-2.0"

[dependencies]
cgmath = "0.2"
glium = "0.6"
image = "0.3"
